/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import tipografias.Fuente;

import battleship.AstuciaNaval;
import battleship.Jugador;
import battleship.TableroFlota;
import battleship.TableroTiro;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author wildg
 */
public class LocalGamePanel extends javax.swing.JPanel  {
    
    Jugador jugador1;
    Jugador jugador2;
    AstuciaNaval partida;
    Display d;
    TableroFlota f1;
    TableroFlota f2;
    TableroTiro  t1;
    TableroTiro  t2;
    int ii;
    public LocalGamePanel(Display d) {
        initComponents();
        this.d = d;
    }
    
    /**
     * Creates new form SetFormationPanel
     */
    public LocalGamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        rowsPanel = new javax.swing.JPanel();
        bgSoundLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        boardNameLabel = new javax.swing.JLabel();
        setFormationButton = new javax.swing.JButton();
        columnsPanel = new javax.swing.JPanel();
        radarLabel = new javax.swing.JLabel();

        setOpaque(false);

        jLayeredPane1.setBackground(java.awt.Color.gray);
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(500, 500));
        jLayeredPane1.setOpaque(true);

        javax.swing.GroupLayout rowsPanelLayout = new javax.swing.GroupLayout(rowsPanel);
        rowsPanel.setLayout(rowsPanelLayout);
        rowsPanelLayout.setHorizontalGroup(
            rowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        rowsPanelLayout.setVerticalGroup(
            rowsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bgSoundLabel.setBackground(java.awt.Color.orange);
        bgSoundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/volume-up.png"))); // NOI18N
        bgSoundLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bgSoundLabelMouseClicked(evt);
            }
        });

        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/backspace-arrow.png"))); // NOI18N
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });

        nameLabel.setBackground(new java.awt.Color(255, 153, 102));
        nameLabel.setFont(Fuente.EuroStyle.getFuente(0, 14));
        nameLabel.setForeground(java.awt.Color.green);
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Jugador");

        boardNameLabel.setBackground(new java.awt.Color(51, 255, 102));
        boardNameLabel.setFont(Fuente.EuroStyle.getFuente(0, 14));
        boardNameLabel.setForeground(java.awt.Color.green);
        boardNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boardNameLabel.setText("Formación de Flota");

        setFormationButton.setBackground(java.awt.Color.green);
        setFormationButton.setFont(Fuente.Impact.getFuente(0, 12));
        setFormationButton.setText("Aceptar");
        setFormationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setFormationButtonActionPerformed(evt);
            }
        });

        columnsPanel.setOpaque(false);

        javax.swing.GroupLayout columnsPanelLayout = new javax.swing.GroupLayout(columnsPanel);
        columnsPanel.setLayout(columnsPanelLayout);
        columnsPanelLayout.setHorizontalGroup(
            columnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        columnsPanelLayout.setVerticalGroup(
            columnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        radarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sources/radar.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bgSoundLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(rowsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boardNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(columnsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(setFormationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boardNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setFormationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(columnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addComponent(rowsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(bgSoundLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(radarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setFormationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setFormationButtonActionPerformed
        // TODO add your handling code here:
        if(ii==0){
            if(jugador1.colocarNaves()){
                System.out.println("bien");
                cover();
                Display.showMessageDialog(d,"Organiza tu flota Jugador 2");
                uncover();
                this.nameLabel.setText("Jugador 2");
                this.jLayeredPane1.removeAll();
                jLayeredPane1.add(f2,new Integer(0));
                ii++;
            }else {
                System.out.println("Formación de flota no válida");
                Display.showMessageDialog(d,"Formación de flota no válida");
            }
        }else if(ii==1){
            if(jugador2.colocarNaves()){
                System.out.println("bien");
                this.jLayeredPane1.removeAll();
                ii++;
            }else {
                System.out.println("Formación de flota no válida");
                Display.showMessageDialog(d,"Formación de flota no válida");
            }
        }
        if(ii==2){
            cover();
            Display.showMessageDialog(d,"Turno jugador 1");
            uncover();
            this.repaint();
            this.boardNameLabel.setText("Tablero de tiro");
            partida = new AstuciaNaval(this.jugador1,this.jugador2,this);
            this.setFormationButton.setVisible(false);
        }
    }//GEN-LAST:event_setFormationButtonActionPerformed

    private void bgSoundLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgSoundLabelMouseClicked
        // TODO add your handling cbgSoundLabele:
        if(this.d.getSoundSw()){
            bgSoundLabel.setIcon(new ImageIcon("src/sources/mute.png"));
        }else {
            bgSoundLabel.setIcon(new ImageIcon("src/sources/volume-up.png"));
        }
        this.d.setBGSound();
    }//GEN-LAST:event_bgSoundLabelMouseClicked

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        cover();
        int se = Display.showConfirmationDialog(d,"Esta seguro que desea salir?");
        uncover();
        if(se==0){
            exit();
        }
    }//GEN-LAST:event_exitLabelMouseClicked

    public void init(){
        initComponents();
        jugador1 = new Jugador();
        jugador2 = new Jugador();
        f1 = this.jugador1.getMiFlota();
        f1.setSize(new Dimension(500,500));
        f2 = this.jugador2.getMiFlota();
        f2.setSize(new Dimension(500,500));
        t1 = this.jugador1.getTableroTiro();
        t1.setSize(new Dimension(500,500));
        t2 = this.jugador2.getTableroTiro();
        t2.setSize(new Dimension(500,500));
        this.nameLabel.setText("Jugador 1");
        jLayeredPane1.add(f1,new Integer(0));
        ii=0;
        cover();
        Display.showMessageDialog(d,"Organiza tu flota Jugador 1");
        uncover();
        columnsPanel.setLayout(new GridLayout(1,10));
        columnsPanel.setOpaque(false);
        JLabel[] u1 = new JLabel[10];
        for (int i = 0; i < 10; i++) {
            u1[i]= new JLabel();
            this.columnsPanel.add(u1[i]);
            u1[i].setHorizontalAlignment(SwingConstants.CENTER);
            u1[i].setText(Integer.toString(i+1));
            u1[i].setForeground(Color.GREEN);
            u1[i].setFont(Fuente.EuroStyle.getFuente(0, 14));
        }
        rowsPanel.setLayout(new GridLayout(10,1));
        rowsPanel.setOpaque(false);
        JLabel[] u2 = new JLabel[10];
        for (int i = 0; i < 10; i++) {
            u2[i]= new JLabel();
            this.rowsPanel.add(u2[i]);
            u2[i].setHorizontalAlignment(SwingConstants.CENTER);
            u2[i].setText(Character.toString((char)(i+65)));
            u2[i].setForeground(Color.GREEN);
            u2[i].setFont(Fuente.EuroStyle.getFuente(0, 14));
        }
        if(this.d.getSoundSw()){
            bgSoundLabel.setIcon(new ImageIcon("src/sources/volume-up.png"));
        }else {
            bgSoundLabel.setIcon(new ImageIcon("src/sources/mute.png"));
        }
    }
    
    public void setTablero(int i){
        this.jLayeredPane1.removeAll();
        if(i==1){
            this.jLayeredPane1.add(t1,0);
            this.nameLabel.setText("Jugador 1");
        }else {
            this.jLayeredPane1.add(t2,0);
            this.nameLabel.setText("Jugador 2");
        }
        this.repaint();
    }
    
    public void cover(){
        radarLabel.setVisible(false);
        this.d.cover();
    }
    
    public void uncover(){
        this.d.uncover();
        radarLabel.setVisible(true);
    }
    
    public void exit(){
        d.setSelectGM();
    }
    
    public void showDialog(String mensaje){
        cover();
        Display.showMessageDialog(d,mensaje);
        uncover();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgSoundLabel;
    private javax.swing.JLabel boardNameLabel;
    private javax.swing.JPanel columnsPanel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel radarLabel;
    private javax.swing.JPanel rowsPanel;
    private javax.swing.JButton setFormationButton;
    // End of variables declaration//GEN-END:variables
}
