/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import battleship.AstuciaNaval;
import battleship.Jugador;
import battleship.TableroFlota;
import battleship.TableroTiro;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author wildg
 */
public class LocalGamePanel extends javax.swing.JPanel  {
    
    Jugador jugador1;
    Jugador jugador2;
    AstuciaNaval partida;
    Display d;
    TableroFlota f1;
    TableroFlota f2;
    TableroTiro  t1;
    TableroTiro  t2;
    int ii;
    public LocalGamePanel(Display d) {
        initComponents();
        this.d = d;
    }
    
    /**
     * Creates new form SetFormationPanel
     */
    public LocalGamePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jugador");

        jButton1.setBackground(java.awt.Color.orange);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(255, 204, 204));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(500, 500));
        jLayeredPane1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.orange);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formación de Flota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(ii==0){
            if(jugador1.colocarNaves()){
                System.out.println("bien");
                this.jLabel1.setText("Jugador 2");
                this.jLayeredPane1.removeAll();
                jLayeredPane1.add(f2,new Integer(0));
                ii++;
            }else {
                System.out.println("mal");
                JOptionPane.showMessageDialog(null, "Mal");
            }
        }else if(ii==1){
            if(jugador2.colocarNaves()){
                System.out.println("bien");
                this.jLabel1.setText("comenzo juego");
                this.jLayeredPane1.removeAll();
                ii++;
            }else {
                System.out.println("mal");
                JOptionPane.showMessageDialog(null, "Mal");
            }
        }
        this.repaint();
        if(ii==2){
            this.jLabel2.setText("Tablero de tiro");
            partida = new AstuciaNaval(this.jugador1,this.jugador2,this);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void init(){
        initComponents();
        jugador1 = new Jugador();
        jugador2 = new Jugador();
        f1 = this.jugador1.getMiFlota();
        f1.setSize(new Dimension(500,500));
        f2 = this.jugador2.getMiFlota();
        f2.setSize(new Dimension(500,500));
        t1 = this.jugador1.getTableroTiro();
        t1.setSize(new Dimension(500,500));
        t2 = this.jugador2.getTableroTiro();
        t2.setSize(new Dimension(500,500));
        this.jLabel1.setText("Jugador 1");
        jLayeredPane1.add(f1,new Integer(0));
        ii=0;
        /*t1.setVisible(true);
        t1.setOpaque(true);*/
    }
    
    public void setTablero(int i){
        this.jLayeredPane1.removeAll();
        if(i==1){
            this.jLayeredPane1.add(t1,0);
            this.jLabel1.setText("Jugador 1");
        }else {
            this.jLayeredPane1.add(t2,0);
            this.jLabel1.setText("Jugador 2");
        }
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
